version: '3.8'

services:
  reverse-proxy:
    image: nginx:latest
    container_name: nginxrp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx
    ports:
      - 80:80
    depends_on:
      - microservice-auth
      - microservice-users
      - microservice-cards
      - microservice-transactions
    networks:
      #- internal-network
      - public-network

  microservice-auth:
    build:
        context: ./MicroServiceAuth
        dockerfile: Dockerfile
    container_name: microservice-auth
    ports:
      - 8083:8083
    networks:
      #- internal-network
      - public-network

  microservice-users:
    build:
        context: ./MicroServiceUsers
        dockerfile: Dockerfile
    container_name: microservice-users
    ports:
      - 8081:8081
    networks:
      #- internal-network
      - public-network

  microservice-cards:
    build:
        context: ./MicroServiceCards
        dockerfile: Dockerfile
    container_name: microservice-cards
    ports:
      - 8084:8084
    networks:
      #- internal-network
      - public-network

  microservice-transactions:
    build:
        context: ./MicroServiceTransactions
        dockerfile: Dockerfile
    container_name: microservice-transactions
    ports:
      - 8082:8082
    networks:
      #- internal-network
      - public-network

networks:
  internal-network:
    internal: true
  public-network: