version: '3.8'

services:
  reverse-proxy:
    image: nginx:latest
    container_name: nginxrp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx
    ports:
      - 80:80
    depends_on:
      - microservice-auth
      - microservice-users
      - microservice-cards
      - microservice-transactions
    networks:
      - public-network

  microservice-auth:
    build:
      context: ./MicroServiceAuth
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    networks:
      public-network:
        aliases:
          - microservice-auth

  microservice-users:
    build:
      context: ./MicroServiceUsers
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks:
      public-network:
        aliases:
          - microservice-users

  microservice-cards:
    build:
      context: ./MicroServiceCards
      dockerfile: Dockerfile
    ports:
      - 8084:8084
    networks:
      public-network:
        aliases:
          - microservice-cards

  microservice-transactions:
    build:
      context: ./MicroServiceTransactions
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    networks:
      public-network:
        aliases:
          - microservice-transactions

networks:
  public-network:
