version: '3.8'

services:
  reverse-proxy:
    image: nginx:latest
    container_name: nginxrp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      # - microservice-auth
      # - microservice-users
      - microservice-cards
      # - microservice-transactions
    networks:
      - internal-network
      - public-network

  # microservice-auth:
  #   build:
  #       context: ./MicroServiceAuth
  #       dockerfile: Dockerfile
  #   ports:
  #     - 8083:8080
  #   networks:
  #     - internal-network

  # microservice-users:
  #   build:
  #       context: ./MicroServiceUsers
  #       dockerfile: Dockerfile
  #   ports:
  #     - 8081:8080
  #   networks:
  #     - internal-network

  microservice-cards:
    build:
        context: ./MicroServiceCards
        dockerfile: Dockerfile
    ports:
      - 8084:8080
    networks:
      - internal-network

  # microservice-transactions:
  #   build:
  #       context: ./MicroServiceTransactions
  #       dockerfile: Dockerfile
  #   ports:
  #     - 8082:8080
  #   networks:
  #     - internal-network

networks:
  internal-network:
    internal: true
  public-network: